urls.py
from django.views.generic.simple import direct_to_template
from django.conf.urls.defaults import *
from bookmarks.views import *
from bookmarks import views
import os
site_media = os.path.join(os.path.dirname(__file__), 'site_media')

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('', 
    #(r'^admin/(.*)', admin.site.root),
    url(r'^admin/', include(admin.site.urls)),
    #browsing
    (r'^$', main_page),
    (r'^popular/$', popular_page),
    (r'^user/(\w+)/$', user_page),
    (r'^tag/([^\s]+)/$',tag_page),
    (r'^search/$', search_page),
    (r'^bookmark/(\d+)/$', bookmark_page),
    # session mgt
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^register/$',register_page),
    (r'^register/success/$', direct_to_template,{'template': 'registration/register_success.html'}),
    # friends
    (r'^friends/(\w+)/$', friends_page),
    (r'^friend/add/$', friend_add),
    (r'^friend/invite/$', friend_invite),
    (r'^friend/accept/(\w+)/$', friend_accept),
   #Account mgt 
    (r'^tag/$',tag_cloud_page),
    (r'^save/$', bookmark_save_page),
    (r'^vote/$', bookmark_vote_page),

    #comment
    (r'^comments/',include('django.contrib.comments.urls')),
   # site media 
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': site_media}),
    
    # created model form 
    (r'^contact/$',contact_page),
    (r'^contact/edit/(?P<p_id>\d+)$',edit_contact_page),
    (r'^contact/success/$', direct_to_template,{'template': 'registration/contact_success.html'}),
    (r'^contact/edit/success/$',direct_to_template,{'template':'registration/contact_success.html'}),
)

bookmarks/models.py
from django.db import models

from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings



class Link(models.Model):
    url = models.URLField(unique=True)
    def __unicode__(self):
        return self.url

# Create your models here.

from django.contrib.auth.models import User
class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)
    def __unicode__(self):
        return u'%s, %s' % (self.user.username, self.link.url)

#Thismodel holds the tag name and its bookmarks
class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)
    def __unicode__(self):
        return self.name


class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)
    def __unicode__(self):
        return u'%s, %s' % (self.bookmark, self.votes)


class Friendship(models.Model):
    from_friend = models.ForeignKey(
    User, related_name='friend_set')
    to_friend = models.ForeignKey(User, related_name='to_friend_set')
    def __unicode__(self):
        return u'%s, %s' % (self.from_friend.username,self.to_friend.username)
    class Meta:
        unique_together = (('to_friend', 'from_friend'), )
        #permissions = (('can_list_friend_bookmarks','Can list friend bookmarks'), )

class Invitation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s, %s' % (self.sender.username, self.email)
    def send(self):
        subject = u'Invitation to join Django Bookmarks'
        link = 'http://%s/friend/accept/%s/' % (settings.SITE_HOST,self.code)
        template = get_template('invitation_email.txt')
        context = Context({'name': self.name,'link': link,'sender': self.sender.username,})
        message = template.render(context)
        send_mail(subject, message,settings.DEFAULT_FROM_EMAIL, [self.email])

class Contact(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    msg = models.TextField()
    phone = models.IntegerField()

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

        <title>{% block title %}  {% endblock %}</title><!--title to the page -->
        
            <link href="/site_media/css/bootstrap.css" rel="stylesheet">
	            <style>
	                .centerthis {
                        width: 300px;
                        margin:0 auto;
                        }	
	                .form-signin {
                        max-width: 300px;
                        padding: 9px 9px 9px;
                        margin: 0 auto 10px;
                        background-color: #f1f1f1;
                        border: 2px solid #e5e5e5;
                        -webkit-border-radius: 10px;
                        -moz-border-radius: 10px;
                        border-radius: 5px;
                        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                       -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                        box-shadow: 0 1px 2px rgba(0,0,0,.05);
                        }
        
                    .form-signin .form-signin-heading{
                        margin-bottom: 1px;
                        margin-top: 5px;
                        }
                    
                    .form-signin input[type="text"],
                    .form-signin input[type="password"]{
                        font-size: 12px;
                        height: auto;
                        margin-bottom: 5px;
                        margin-top: 5px;
                        padding: 7px 9px;
                        }
	                .tag-cloud {text-align: center;}
                    .tag-cloud a {margin: 0 0.2em;}
                    .tag-cloud-0 {font-size:100%;}                       
                    .tag-cloud-0 {font-size:120%;}                       
                    .tag-cloud-0 {font-size:140%;}                       
                    .tag-cloud-0 {font-size:160%;}                       
                    .tag-cloud-0 {font-size:180%;}                       
                    .tag-cloud-0 {font-size:200%;}                       
                    textarea {display: block;}
                    .comment {
                    margin: 1em;
                    padding: 5px;
                    border: 1px solid #000;
                    }
                    ul.messages {
                    border: 1px dashed #000;
                    margin: 1em 4em;
                    padding: 1em;
                    }
                    input {
                        display: block;
                    }
                    #t1{border:1;}

                
                body { padding-top:30px }
	        </style>
	<link href="/site_media/css/bootstrap-responsive.css" rel="stylesheet">
    <script type="text/javascript" src="/site_media/jquery.js"></script>
</head>



<body>
    <div class="navbar navbar-inverse navbar-fixed-top" >
	    <div class="navbar-inner">
		    <div class="container" color="gray">
			    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> </button>
			
            <a class="brand" href="#">Django Bookmarks</a>
			    <div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
			       		    <li><a href="/">home</a>
			       		    <li><a href="/popular/">popular</a>
                            <li class="active" >{% if user.is_authenticated %}</li>
								<li><a href="/user/{{ user.username }}/">{{user.username}}</a></li>
								     <li><a href="/save">submit</a></li>
									 <li><a href="/search/">search</a></li>
                                            <li><a href="/logout">logout</a></li>
									    {% else %}	
											<li><a href="/login/">login | </a></li>
				              						<li><a href="/register/">register | </a></li>
											<li><a href="/contact/">contact | </a></li>
						 			   {% endif %}
						</ul>
					</div>
				</div>
        	</div><!--/.nav-collapse -->
	      </div>
	</div>



<div class="container ">
<div class="row" >
	<div class="span12 ">
	    {% block containt %} {% endblock %}
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li>{{ message }}</li>
{% endfor %}
</ul>
{% endif %}
	</div>
</div>
</div> <!-- /container -->

  
  
</body>
</html>

templates/bookmark_list.html
{% if bookmarks %}
    <ul class="bookmarks">
        {% for bookmark in bookmarks %}
        <li>
            <a href="{{ bookmark.link.url }}" class="title">{{ bookmark.title }}</a>
            
            {% if show_edit %}
            <a href="/save/?url={{ bookmark.link.url|urlencode }}"
            class="edit">[edit]</a>
            {% endif %} 
            
            
            <br/>
            
            {% if show_tags %}
                Tags:
                {% if bookmark.tag_set.all %}
                <ul class="tags">
                {% for tag in bookmark.tag_set.all %}
                    <li>
                        <a href="/tag/{{ tag.name|urlencode}}/">{{ tag.name }}</a>
                    </li>
                {% endfor %}
                </ul>
                {% else %}
                    None.
                {% endif %}
                <br/>
            {% endif %}
            {% if show_user %}
                Posted by:
                <a href="/user/{{ bookmark.user.username }}/"class="username">{{ bookmark.user.username }}</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>


    {% if show_paginator %}
        <div class="paginator">
            {% if has_prev %}
                <a href="?page={{ prev_page }}">&laquo; Previous</a>
            {% endif %}
            {% if has_next %}
                <a href="?page={{ next_page }}">Next &raquo;</a>
            {% endif %}
            (Page {{ page }} of {{ pages }})
        </div>
    {% endif %} 

{% else %}
    <p>No bookmarks found.</p>
{% endif %}

templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}
{% block title %}Bookmark:
    {{ shared_bookmark.bookmark.title }}{% endblock %}
{% block head %}
    <a href="/vote/?id={{ shared_bookmark.id }}"
    class="vote">[+]</a>
    
    <a href="{{ shared_bookmark.bookmark.link.url }}"
    class="title">{{ shared_bookmark.bookmark.title }}</a>
{% endblock %}

{% block containt %}
Posted By:
<a href="/user/{{ shared_bookmark.bookmark.user.username }}/"
class="username">
{{ shared_bookmark.bookmark.user.username }}</a> |
<span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>

<h2>comments</h2>

{% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}

{% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}

{% for comment in comment_list %}
    <div class="comment">
    <p><b>{{ comment.user.username }}</b> said:</p>
    {{ comment.comment|escape|urlizetrunc:40|linebreaks }}
    </div>
{% endfor %}
<p>Number of comments: {{ comment_count }}</p>
{% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id %}

{% endblock %}

templates/bookmark_save.html
{% extends "base.html" %}
{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}
{% block containt %}
<form method="post" action=".">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save" />
</form>
{% endblock %}

templates/friend_invite.html
{% extends "base.html" %}
{% block title %}Invite A Friend{% endblock %}
{% block head %}Invite A Friend{% endblock %}

{% block containt %}
    Enter your friend name and email below,
    and click "send invite" to invite your friend to join the site:
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send invite" />
    </form>
{% endblock %}

templates/friends_page.html
{% extends "base.html" %}
{% block title %}Friends for {{ username }}{% endblock %}
{% block head %}Friends for {{ username }}{% endblock %}

{% block containt %}
    <h2>Friend List</h2>
    {% if friends %}
        <ul class="friends">
        {% for friend in friends %}
            <li><a href="/user/{{ friend.username }}/">{{ friend.username }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No friends found.</p>
    {% endif %}
    <a href="/friend/invite/">Invite a friend!</a>
    <h2>Latest Friend Bookmarks</h2>
    {% include "bookmark_list.html" %}
{% endblock %}

templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block containt %}
	{% if user.username %}
		<p>Welcome {{ user.username }}!
		Here you can store and share bookmarks!</p>
	{% else %}
		<p>Welcome anonymous user!
		You need to <a href="/login/">login</a>
		before you can store and share bookmarks.</p>
	{% endif %}
    <h2>Bookmarks Shared by Users</h2>
    {% include "shared_bookmark_list.html" %}
{% endblock %}

templates/popular_page.html
{% extends "base.html" %}
{%block title %}Popular Bookmarks{% endblock %}
{%block head %}Popular Bookmarks{% endblock %}
{%block containt %}
    {% include "shared_bookmark_list.html" %}
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block containt %}
<form id="search-form" method="get" action=".">
{{ form.as_p }}
<input type="submit" value="search" />
</form>
<div id="search-results">
{% if show_results %}
{% include "bookmark_list.html" %}
{% endif %}
</div>
{% endblock %}

templates/shared_bookmark_list.html
{% if shared_bookmarks %}
<ul class="bookmarks">
    {% for shared_bookmark in shared_bookmarks %}
        <li>
            <a href="/vote/?id={{ shared_bookmark.id }}"
            class="vote">[+]</a>
            <a href="{{shared_bookmark.bookmark.link.url}}"
                class="title">{{shared_bookmark.bookmark.title}}</a>
            </br>
            posted By:
            <a href="/user/{{ shared_bookmark.bookmark.user.username }}/"
                class="username">{{ shared_bookmark.bookmark.user.username }}</a> |
                <span class="vote-count">Votes:
                {{ shared_bookmark.votes }}</span> |
                <a href="/bookmark/{{ shared_bookmark.id }}/">Comments</a>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>No Bookmark found</p>
{% endif %}

templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block containt %}
    <div id="tag-cloud">
      {% for tag in tags %}
        <a href="/tag/{{ tag.name|urlencode }}/" 
            class="tag-cloud-{{ tag.weight }}">{{ tag.name }}</a>
      {% endfor %}
    </div>
{% endblock %}

templates/tag_page.html
{% extends "base.html" %}
{% block title%}Tag: {{ tag_name }} {% endblock %}
{% block head%}Bookmark for tag: {{ tag_name }} {% endblock %}
{% block containt%}
    {% include "bookmark_list.html" %}
{% endblock %}

templates/user_page.html
{% extends "base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}
{% block containt %}
    {% ifequal user.username username %}
        <a href="/friends/{{ username }}/">view your friends</a>
    {% else %}
        {% if is_friend %}
            <a href="/friends/{{ user.username }}/">{{ username }} is a friend of yours</a>
        {% else %}
            <a href="/friend/add/?username={{ username }}">add {{ username }} to your friends</a>
        {% endif %}
            - <a href="/friends/{{ username }}/">view {{username }}'s friends</a>
    {% endifequal %}
	{% include "bookmark_list.html"%}
    {% comment %}
    {% if bookmarks %}
		<ul>
		    {% for bookmark in bookmarks %}
		        <li><a href="{{ bookmark.link.url }}">{{ bookmark.title }}</a></li>
		    {% endfor %}
		</ul>
	{% else %}
		<p>No bookmarks found.</p>
	{% endif %}
    {% endcomment %}
{% endblock %}